version: '3'

networks:
  greedie_network:
    driver: bridge
    external: true

services:
  mysql:
    image: mysql
    networks:
      - greedie_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-init.d
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  membership-service:
    restart: on-failure
    image: membership-service:0.0.0
    networks:
      - greedie_network
    ports:
      - 8080
      - "8083:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  money-service:
    restart: on-failure
    image: money-service:0.0.0
    networks:
      - greedie_network
    ports:
      - 8080
      - "8084:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
